#!/bin/sh

[ ! -f /etc/config/wireless ] && wifi config

# Aktifkan radio
uci set wireless.radio0.disabled='0'
uci set wireless.radio0.country='ID'

# Aktifkan iface AP
uci set wireless.default_radio0.disabled='0'
uci set wireless.default_radio0.mode='ap'
uci set wireless.default_radio0.network='lan'
uci set wireless.default_radio0.ssid='Raspi4'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='12345678'

uci commit wireless

sleep 5
wifi up

exit 0
