#!/bin/sh

mount -o remount,rw /

sed -i "s|boardinfo.release.revision|(L.isObject(boardinfo.release)?boardinfo.release.description+'':'')|" \
/www/luci-static/resources/view/status/include/10_system.js

# Patch OPENWRT_RELEASE
sed -i 's|^OPENWRT_RELEASE=.*|OPENWRT_RELEASE="OpenWrt 25.12.0 by Yogxx"|' \
/usr/lib/os-release

rm -f /tmp/luci-indexcache

exit 0
