#!/bin/sh

# Remount rootfs ext4
mount -o remount,rw /

# Patch Firmware Version di LuCI
sed -i "s|_('Firmware Version').*|_('Firmware Version'),(L.isObject(boardinfo.release)?boardinfo.release.description+'':'')|" \
/www/luci-static/resources/view/status/include/10_system.js

# Bersihkan cache LuCI
rm -f /tmp/luci-indexcache

exit 0
