#!/bin/sh

# Buat direktori jika belum ada
mkdir -p /usr/lib/lua/luci/controller
mkdir -p /usr/lib/lua/luci/view

# Menyalin file tinyfm.lua ke lokasi yang benar
cat <<EOF > /usr/lib/lua/luci/controller/tinyfm.lua
module("luci.controller.tinyfm", package.seeall)
function index()
    entry({"admin","services","tinyfm"}, template("tinyfm"), _("File Manager"), 47).leaf=true
end
EOF

# Menyalin file tinyfm.htm ke lokasi yang benar
cat <<EOF > /usr/lib/lua/luci/view/tinyfm.htm
<%+header%>
<div class="cbi-map"><br>
<iframe id="tinyfm" style="width: 100%; min-height: 100vh; border: none; border-radius: 2px;"></iframe>
</div>
<script type="text/javascript">
document.getElementById("tinyfm").src = window.location.protocol + "//" + window.location.host + "/tinyfm/tinyfm.php";
</script>
<%+footer%>
EOF

# Set permission agar file bisa diakses oleh user luci
chmod 644 /usr/lib/lua/luci/controller/tinyfm.lua
chmod 644 /usr/lib/lua/luci/view/tinyfm.htm

# Menandai skrip ini sudah dijalankan
touch /etc/uci-defaults/99-tinyfm
