name: OpenWrt RPi4

on:
  workflow_dispatch:
    inputs:
      rootfs_size:
        description: "RootFS size in MB"
        default: "1024"
        required: true
      ipk_url:
        description: "URL custom IPK (optional)"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zstd wget

      - name: Download ImageBuilder
        run: |
          wget https://downloads.openwrt.org/releases/24.10.5/targets/bcm27xx/bcm2711/openwrt-imagebuilder-24.10.5-bcm27xx-bcm2711.Linux-x86_64.tar.zst
          tar --zstd -xf openwrt-imagebuilder-24.10.5-bcm27xx-bcm2711.Linux-x86_64.tar.zst

      - name: Inject IPK (if provided)
        if: ${{ github.event.inputs.ipk_url != '' }}
        run: |
          wget -O custom.ipk "${{ github.event.inputs.ipk_url }}"
          cp custom.ipk openwrt-imagebuilder-*/packages/

      - name: Build Firmware
        run: |
          cd openwrt-imagebuilder-24.10.5-bcm27xx-bcm2711.Linux-x86_64
          echo "CONFIG_TARGET_ROOTFS_PARTSIZE=${{ github.event.inputs.rootfs_size }}" >> .config

          make image \
            PROFILE="rpi-4" \
            PACKAGES="kmod-mii kmod-usb-core kmod-usb-net kmod-usb-net-rtl8150 kmod-usb-net-rtl8152 kmod-usb-net-asix kmod-usb-net-asix-ax88179 \
            kmod-usb-net-rndis kmod-usb-net-cdc-ncm kmod-usb-net-huawei-cdc-ncm kmod-usb-net-cdc-ether kmod-usb-net-qmi-wwan kmod-usb-net-sierrawireless \
            kmod-usb-serial kmod-usb-serial-sierrawireless kmod-usb-serial-qualcomm kmod-usb-serial-wwan kmod-usb-serial-option kmod-usb-acm usbutils \
            kmod-tun kmod-nft-tproxy kmod-nft-socket kmod-inet-diag kmod-netlink-diag \
            \
            luci-proto-modemmanager \
            \
            kmod-mii kmod-usb-core kmod-usb-net kmod-usb-net-rtl8150 kmod-usb-net-rtl8152 kmod-usb-net-asix kmod-usb-net-asix-ax88179 \
            kmod-usb-net-rndis kmod-usb-net-cdc-ncm kmod-usb-net-huawei-cdc-ncm kmod-usb-net-cdc-ether kmod-usb-net-qmi-wwan kmod-usb-net-sierrawireless \
            kmod-usb-serial kmod-usb-serial-sierrawireless kmod-usb-serial-qualcomm kmod-usb-serial-wwan kmod-usb-serial-option kmod-usb-acm usbutils \
            kmod-tun kmod-nft-tproxy kmod-nft-socket kmod-inet-diag kmod-netlink-diag \
            \
            chat comgt adb modemmanager libmbim libqmi bzip2 gzip unzip libqrtr-glib mbim-utils qmi-utils sms-tool umbim uqmi libuci-lua libacl liblzma libzstd \
            libinotifytools inotifywait xz-utils xz tar wget bash nano iperf3 ip-full firewall4 yq jq curl ca-bundle \
            \
            coreutils coreutils-stat coreutils-nohup coreutils-base64 \
            \
            libyaml libruby3.3 ruby ruby-yaml ruby-stringio ruby-psych ruby-pstore ruby-enc ruby-digest ruby-date ruby-bigdecimal \
            \
            perl perl-cgi perlbase-xsloader perl-http-date perlbase-utf8" \
            FILES="../files"

      - uses: actions/upload-artifact@v4
        with:
          name: openwrt-rpi4-custom
          path: openwrt-imagebuilder-*/bin/targets/
